[package]
name = "npmpink-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
npmpink-core = { path = "../npmpink-core", version = "0.1.0" }

# External 
crossterm = "0.27.0"
tui = "0.19.0"
anyhow = "1.0.86"
